#dataset_root: /home/martinvalentine/Desktop/CSLR-VSL/data/processed/VSL_Sample/features/256x256px
dataset_root: /data/interim/VSL/frame/256x256px
dict_path: /data/processed/VSL_Benchmark/gloss_dict.npy
evaluation_dir: /src/cslr_vsl/evaluation/slr_eval
evaluation_prefix: vsl-ground-truth