#dataset_root: /home/martinvalentine/Desktop/CSLR-VSL/data/processed/VSL_Sample/features/256x256px
dataset_root: /home/martinvalentine/Desktop/CSLR-VSL/data/interim/VSL_Benchmark
dict_path: /home/martinvalentine/Desktop/CSLR-VSL/CorrNet/preprocess/VSL_Benchmark/gloss_dict.npy
evaluation_dir: /home/martinvalentine/Desktop/CSLR-VSL/CorrNet/evaluation/slr_eval
evaluation_prefix: vsl-ground-truth